# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7dd025bbdc7d4fc1c5310126a290970f38d84c669bae1b14f5556b06534d90c8e90cc557c328da35daf94d05a44f27662d93e42e7733a6f1edb99a6a8997940

test:
  secret_key_base: 32b8d5b401659dad6f1d7a5cceba4411cb095ad453dc4f676781985c488946a45db9b88f279734264ea8ecf8bafe364e1871743a1529768df9bcd23a78c0dc2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
